# Generated by Django 4.0.3 on 2022-03-15 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0002_alter_memo_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memo',
            options={'ordering': ['-created']},
        ),
    ]
